### ISSUE TITLE
LaunchNIVeriStand Fails with Error -307652

### ISSUE THREAD

**Issue by agomez08** [ni/niveristand-python#36]
Using VeriStand 2020 R4 and the next example:
https://github.com/ni/niveristand-python/blob/master/examples/legacy_mix.py

Script would fail in line 11: NIVeriStand.LaunchNIVeriStand()
Error -307652, Could not launch VeriStand.

Inspecting this file: https://github.com/ni/niveristand-python/blob/master/src/niveristand/legacy/NIVeriStand.py
Line 41 tries doing the next: 

veristand = os.path.join(path, "NI VeriStand.exe")

But my installation does not have an "NI VeriStand.exe". Not sure when it changed, but for 2020 R4 the file in C:\Program Files\National Instruments\VeriStand 2020 is called "VeriStand.exe".

This may be causing this issue.

**Comment by jmartinez44** [comment]
So I also ran into this same error but I believe line 41 is not the source of the issue. The reason is that the function tries to open up VeriStand using the old VeriStand name (which was once NI VeriStand.exe) and fails if you have a newer version of VeriStand, but the the script will try to launch the VeriStand Project Explorer.exe which **will** work with newer versions of VeriStand. The issue is that line 39 calls the base_assembly_path() function which appends 'nivs.lib' and 'Reference Assemblies' to the end of the VeriStand installation path which returns an invalid path. That throws the Error -307652.

**Comment by agomez08** [comment]
Makes sense. Thanks for further exploring and commenting here on the root cause.
